---
title: Dylan Karlsson
author: Dylan Karlsson
email: karlsson.dylan@gmail.com
description: ''
baseurl: ''
url: dylankarlsson.github.io
defaults:
- scope: ''
  values: ''
plugins:
- jekyll-feed
- jekyll-menus
